version: '3.8'

services:
  mysql:
    container_name: bonheur-mysql
    image: mysql:5.7
    ports:
      - "3308:3306"
    volumes:
      - mysql-volume:/bitnami/mysql
    restart: unless-stopped
    environment:
      - MYSQL_USER=bonheur
      - MYSQL_PASSWORD=bo123
      - MYSQL_DATABASE=bonheur_local
      - MYSQL_ROOT_PASSWORD=bo123
    networks:
      - bonheur-network
  redis:
    image: redis:6.0
    container_name: bonheur-redis
    command: redis-server --port 6379
    ports:
      - '6379:6379'
    restart: unless-stopped
    volumes:
      - redis-volume:/data
    networks:
      - bonheur-network
  web:
    container_name: bonheur-server
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3308/bonheur_local?autoReconnect=true&useSSL=false
    depends_on:
      - redis
      - mysql
    networks:
      - bonheur-network

volumes:
  mysql-volume:
    driver: local
  redis-volume:
    driver: local

networks:
  bonheur-network:
    driver: bridge